import { Skill, SkillExecutionContext, SkillResult } from '../../loader.js';
import { browserExecutor } from '../../../execution/browser.js';
import { createProvider } from '../../../core/llm/index.js';
import { configLoader } from '../../../config/loader.js';

export const manifest: Skill['manifest'] = {
    name: 'deep_research',
    version: '1.0.0',
    description: 'Conducts deep, multi-step research on a topic, reading multiple sources and synthesizing a report.',
    triggers: [
        { type: 'keyword', value: 'research', description: 'Research a topic thoroughly' },
        { type: 'command', value: '/research', description: 'Start deep research agent' },
    ],
    parameters: [
        {
            name: 'topic',
            type: 'string',
            required: true,
            description: 'The topic to research',
        },
        {
            name: 'depth',
            type: 'number',
            required: false,
            description: 'Depth of research (1-5)',
            default: 3,
        },
    ],
    permissions: ['browser', 'llm'],
    examples: [
        'research quantum computing trends',
        '/research "latest AI models" --depth 2',
    ],
};

export class DeepResearchSkill implements Skill {
    manifest = manifest;

    async execute(context: SkillExecutionContext): Promise<SkillResult> {
        const { parameters } = context;
        const topic = parameters.topic as string;
        const depth = (parameters.depth as number) || 2;
        const report: string[] = [];

        if (!topic) {
            return { success: false, output: 'Topic is required' };
        }

        try {
            const config = await configLoader.load();
            const llm = createProvider(config.llm);

            // 1. Plan Phase
            report.push(`# Research Report: ${topic}\n`);
            report.push(`*Generated by Deep Research Agent*\n`);

            console.log(`[Research] Planning research on: ${topic}`);

            // 2. Search Phase
            const searchUrl = `https://html.duckduckgo.com/html/?q=${encodeURIComponent(topic)}`;
            await browserExecutor.navigate({ url: searchUrl });
            await new Promise((resolve) => setTimeout(resolve, 2000)); // Wait for load

            // Extract results
            const searchResults = await browserExecutor.evaluate(`(() => {
        const results = [];
        const elements = document.querySelectorAll('.result__body');
        elements.forEach(el => {
            const titleEl = el.querySelector('.result__title .result__a');
            const snippetEl = el.querySelector('.result__snippet');
            if (titleEl && snippetEl) {
                results.push({
                    title: titleEl.innerText,
                    link: titleEl.href,
                    snippet: snippetEl.innerText
                });
            }
        });
        return results.slice(0, ${depth + 2}); 
      })()`);

            if (!searchResults.success || !searchResults.data) {
                throw new Error('Failed to retrieve search results');
            }

            const links = JSON.parse(searchResults.data as string) as Array<{ title: string; link: string; snippet: string }>;
            report.push(`## Sources Analyzed\n`);
            links.forEach(l => report.push(`- [${l.title}](${l.link})`));
            report.push('\n');

            // 3. Deep Reading Phase
            let synthesizedContent = '';

            for (const link of links) {
                if (!link.link.startsWith('http')) continue;

                console.log(`[Research] Reading: ${link.title}`);
                try {
                    await browserExecutor.navigate({ url: link.link, timeout: 15000 }); // Fast timeout
                    const pageContent = await browserExecutor.evaluate(`document.body.innerText`);

                    if (pageContent.success && pageContent.data) {
                        const text = (JSON.parse(pageContent.data as string) as string).substring(0, 5000); // Limit context
                        synthesizedContent += `Source: ${link.title}\nContent: ${text}\n\n`;
                    }
                } catch (e) {
                    console.warn(`[Research] Failed to read ${link.link}: ${e}`);
                }
            }

            // 4. Synthesis Phase
            console.log(`[Research] Synthesizing final report...`);
            const synthesisPrompt = `
        You are an expert researcher. Synthesize a comprehensive report on "${topic}" based on the following gathered information.
        Format accurately in Markdown with headers, bullet points, and code blocks if relevant.
        Cite sources where possible.

        ${synthesizedContent}
      `;

            const finalReport = await llm.complete([
                { role: 'system', content: 'You are a precise and thorough research analyst.' },
                { role: 'user', content: synthesisPrompt }
            ], {
                maxTokens: 2000,
                temperature: 0.5
            });

            report.push(`## Findings\n\n${finalReport.content}`);

            return {
                success: true,
                output: report.join('\n'),
                data: {
                    topic,
                    sources: links,
                    fullReport: finalReport.content
                }
            };

        } catch (error) {
            return {
                success: false,
                output: `Research failed: ${error instanceof Error ? error.message : String(error)}`,
            };
        }
    }
}
