import React, { useState, useCallback } from 'react';
import { Box, Text, useInput } from 'ink';
import Spinner from 'ink-spinner';

type ResearchDepth = 'quick' | 'standard' | 'deep' | 'expert';

type Phase =
  | 'idle'
  | 'input'
  | 'running'
  | 'done';

interface ResearchStep {
  label: string;
  done: boolean;
  running: boolean;
}

const DEPTH_LABELS: Record<ResearchDepth, string> = {
  quick:    '⚡ Quick    (~30s)',
  standard: '🔍 Standard (~2m)',
  deep:     '🧬 Deep     (~5m)',
  expert:   '🎓 Expert   (~10m)',
};

const STEPS: string[] = [
  'Decomposing query into sub-questions',
  'Searching primary sources',
  'Searching academic databases',
  'Scraping relevant web pages',
  'Extracting key facts',
  'Cross-referencing sources',
  'Synthesising findings',
  'Generating structured report',
];

export default function ResearchView() {
  const [phase, setPhase] = useState<Phase>('idle');
  const [query, setQuery] = useState('');
  const [depth, setDepth] = useState<ResearchDepth>('standard');
  const [depthCursor, setDepthCursor] = useState(1);
  const [steps, setSteps] = useState<ResearchStep[]>([]);
  const [report, setReport] = useState<string[]>([]);
  const [inputBuffer, setInputBuffer] = useState('');
  const [stepIndex, setStepIndex] = useState(0);

  const startResearch = useCallback(() => {
    if (!query.trim()) return;
    const initial = STEPS.map((s) => ({ label: s, done: false, running: false }));
    initial[0] = { ...initial[0], running: true };
    setSteps(initial);
    setStepIndex(0);
    setPhase('running');

    let current = 0;
    const interval = setInterval(() => {
      setSteps((prev) => {
        const next = [...prev];
        next[current] = { ...next[current], done: true, running: false };
        if (current + 1 < next.length) {
          next[current + 1] = { ...next[current + 1], running: true };
        }
        return next;
      });
      setStepIndex(current + 1);
      current++;
      if (current >= STEPS.length) {
        clearInterval(interval);
        setReport([
          `# Research Report: ${query}`,
          '',
          '## Executive Summary',
          `This report provides a ${depth}-depth analysis of "${query}", synthesising information from multiple sources.`,
          '',
          '## Key Findings',
          '1. The field has seen significant advances in the past 12 months',
          '2. Three dominant frameworks have emerged with distinct trade-offs',
          '3. Open-source alternatives now match commercial solutions in quality',
          '4. Practical adoption is accelerating across enterprise sectors',
          '',
          '## Sources',
          '• arxiv.org/abs/2501.12345 — Primary research paper',
          '• github.com/example/project — Reference implementation',
          '• blog.openai.com — Official documentation',
          `• ${12 + depthCursor * 3} additional sources referenced`,
          '',
          '---',
          `Report generated by AutoResearcher (${depth} depth) · ${STEPS.length} steps completed`,
        ]);
        setPhase('done');
      }
    }, 600);
  }, [query, depth, depthCursor]);

  useInput((input, key) => {
    if (phase === 'idle') {
      const depths = Object.keys(DEPTH_LABELS) as ResearchDepth[];
      if (key.upArrow)   setDepthCursor((c) => (c - 1 + depths.length) % depths.length);
      if (key.downArrow) setDepthCursor((c) => (c + 1) % depths.length);
      if (key.return) {
        setDepth(depths[depthCursor]);
        setPhase('input');
      }
    } else if (phase === 'input') {
      if (key.return) {
        setQuery(inputBuffer.trim());
        if (inputBuffer.trim()) startResearch();
      } else if (key.backspace || key.delete) {
        setInputBuffer((b) => b.slice(0, -1));
      } else if (input && !key.ctrl && !key.meta) {
        setInputBuffer((b) => b + input);
      }
    } else if (phase === 'done') {
      if (key.return || input === 'r') {
        setPhase('idle');
        setQuery('');
        setInputBuffer('');
        setSteps([]);
        setReport([]);
      }
    }
  });

  const depths = Object.entries(DEPTH_LABELS) as [ResearchDepth, string][];

  return (
    <Box flexDirection="column" padding={1}>
      <Box marginBottom={1}>
        <Text bold color="cyan">🔬 Research Assistant</Text>
        <Text color="gray" dimColor> — AutoResearcher</Text>
      </Box>

      {phase === 'idle' && (
        <Box flexDirection="column">
          <Text color="white">Select research depth:</Text>
          <Box flexDirection="column" marginTop={1} marginLeft={2}>
            {depths.map(([d, label], idx) => (
              <Box key={d} marginBottom={0}>
                <Text
                  color={depthCursor === idx ? 'cyan' : 'gray'}
                  bold={depthCursor === idx}
                >
                  {depthCursor === idx ? '▶ ' : '  '}{label}
                </Text>
              </Box>
            ))}
          </Box>
          <Box marginTop={1}>
            <Text color="gray" dimColor>↑↓ to select · Enter to continue</Text>
          </Box>
        </Box>
      )}

      {phase === 'input' && (
        <Box flexDirection="column">
          <Text color="white">
            Depth: <Text color="cyan" bold>{DEPTH_LABELS[depth]}</Text>
          </Text>
          <Box marginTop={1}>
            <Text color="white">Enter research query: </Text>
            <Text color="cyan">{inputBuffer}<Text color="gray">█</Text></Text>
          </Box>
          <Box marginTop={1}>
            <Text color="gray" dimColor>Type your query · Enter to start research</Text>
          </Box>
        </Box>
      )}

      {phase === 'running' && (
        <Box flexDirection="column">
          <Text color="white">
            Researching: <Text color="cyan" bold>&quot;{query}&quot;</Text>
          </Text>
          <Box flexDirection="column" marginTop={1} marginLeft={2}>
            {steps.map((step, idx) => (
              <Box key={idx} marginBottom={0}>
                {step.done && <Text color="green">✓ </Text>}
                {step.running && (
                  <Text color="cyan">
                    <Spinner type="dots" />
                    {' '}
                  </Text>
                )}
                {!step.done && !step.running && <Text color="gray">○ </Text>}
                <Text
                  color={step.done ? 'green' : step.running ? 'cyan' : 'gray'}
                  dimColor={!step.done && !step.running}
                >
                  {step.label}
                </Text>
              </Box>
            ))}
          </Box>
          <Box marginTop={1}>
            <Text color="gray" dimColor>
              Step {Math.min(stepIndex + 1, STEPS.length)}/{STEPS.length} · Processing…
            </Text>
          </Box>
        </Box>
      )}

      {phase === 'done' && (
        <Box flexDirection="column">
          <Box marginBottom={1}>
            <Text color="green" bold>✓ Research complete!</Text>
          </Box>
          <Box
            borderStyle="round"
            borderColor="cyan"
            paddingX={2}
            paddingY={1}
            flexDirection="column"
          >
            {report.map((line, idx) => (
              <Text
                key={idx}
                bold={line.startsWith('#')}
                color={
                  line.startsWith('##') ? 'cyan' :
                  line.startsWith('#') ? 'white' :
                  line.startsWith('•') ? 'green' :
                  line.startsWith('---') ? 'gray' :
                  'white'
                }
                dimColor={line.startsWith('---') || line === ''}
              >
                {line}
              </Text>
            ))}
          </Box>
          <Box marginTop={1}>
            <Text color="gray" dimColor>Press Enter or [R] for new research · ESC to go back</Text>
          </Box>
        </Box>
      )}
    </Box>
  );
}
