import { randomUUID } from 'crypto';
import { exec } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs';
import * as path from 'path';

const execAsync = promisify(exec);

export interface SymphonySpec {
  name: string;
  description: string;
  task: string;
  workspace?: string;
  branch?: string;
  maxDuration?: number;
  notifyOnComplete?: boolean;
  autoMerge?: boolean;
}

export interface SymphonyRun {
  id: string;
  spec: SymphonySpec;
  status: 'pending' | 'preparing' | 'running' | 'completed' | 'failed' | 'reviewing';
  workspacePath: string;
  branch: string;
  commitSha?: string;
  startedAt: Date;
  completedAt?: Date;
  summary?: string;
  changes?: SymphonyChange[];
  reviewStatus?: 'pending' | 'accepted' | 'rejected';
}

export interface SymphonyChange {
  file: string;
  additions: number;
  deletions: number;
  status: 'added' | 'modified' | 'deleted';
}

export class SymphonyOrchestrator {
  private runs: Map<string, SymphonyRun> = new Map();
  private workspaceRoot: string;
  private baseWorkspace: string;
  private notification?: { telegram?: string; discord?: string };

  constructor(
    options: {
      workspaceRoot?: string;
      baseWorkspace?: string;
      notification?: { telegram?: string; discord?: string };
    } = {}
  ) {
    this.workspaceRoot = options.workspaceRoot || path.join(process.cwd(), '.symphony');
    this.baseWorkspace = options.baseWorkspace || process.cwd();
    this.notification = options.notification;

    if (!fs.existsSync(this.workspaceRoot)) {
      fs.mkdirSync(this.workspaceRoot, { recursive: true });
    }
  }

  async createRun(spec: SymphonySpec): Promise<SymphonyRun> {
    const runId = randomUUID();
    const branchName = spec.branch || `symphony/${runId.slice(0, 8)}`;
    const workspacePath = spec.workspace || path.join(this.workspaceRoot, runId);

    const run: SymphonyRun = {
      id: runId,
      spec,
      status: 'preparing',
      workspacePath,
      branch: branchName,
      startedAt: new Date(),
    };

    this.runs.set(runId, run);
    this.prepareWorkspace(run);

    return run;
  }

  private async prepareWorkspace(run: SymphonyRun): Promise<void> {
    run.status = 'preparing';

    try {
      fs.mkdirSync(run.workspacePath, { recursive: true });

      await execAsync(`git clone ${this.baseWorkspace} .`, {
        cwd: run.workspacePath,
      });

      await execAsync(`git checkout -b ${run.branch}`, {
        cwd: run.workspacePath,
      });

      const specPath = path.join(run.workspacePath, 'SYMPHONY.md');
      fs.writeFileSync(specPath, this.generateSpecMarkdown(run.spec));

      await execAsync('git add SYMPHONY.md', { cwd: run.workspacePath });
      await execAsync('git commit -m "Add symphony task spec"', { cwd: run.workspacePath });

      run.status = 'pending';
    } catch (error) {
      run.status = 'failed';
      console.error(`Failed to prepare workspace for run ${run.id}:`, error);
    }
  }

  private generateSpecMarkdown(spec: SymphonySpec): string {
    return `# Symphony Task: ${spec.name}

${spec.description}

## Task
${spec.task}

## Configuration
- Max Duration: ${spec.maxDuration || 3600000}ms
- Auto Merge: ${spec.autoMerge || false}
- Notify on Complete: ${spec.notifyOnComplete !== false}

---
*Generated by Alpicia Symphony Mode*
`;
  }

  async startRun(runId: string, agentExecutor: SymphonyAgentExecutor): Promise<SymphonyRun> {
    const run = this.runs.get(runId);
    if (!run) {
      throw new Error(`Run not found: ${runId}`);
    }

    if (run.status !== 'pending') {
      throw new Error(`Run is not in pending state: ${run.status}`);
    }

    run.status = 'running';

    const timeout = run.spec.maxDuration || 3600000;
    const timeoutPromise = new Promise<void>((_, reject) => {
      setTimeout(() => reject(new Error('Symphony run timed out')), timeout);
    });

    const executionPromise = this.executeTask(run, agentExecutor);

    try {
      await Promise.race([executionPromise, timeoutPromise]);
    } catch (error) {
      run.status = 'failed';
      console.error(`Symphony run ${runId} failed:`, error);
    }

    return run;
  }

  private async executeTask(run: SymphonyRun, executor: SymphonyAgentExecutor): Promise<void> {
    console.log(`Starting symphony execution for run ${run.id}`);

    try {
      const result = await executor.execute({
        workspacePath: run.workspacePath,
        task: run.spec.task,
        branch: run.branch,
      });

      run.summary = result.summary;
      run.changes = result.changes;

      await this.commitResults(run);

      run.status = 'reviewing';

      if (run.spec.notifyOnComplete !== false) {
        await this.sendSummary(run);
      }
    } catch (error) {
      run.status = 'failed';
      run.summary = `Execution failed: ${error instanceof Error ? error.message : String(error)}`;
    }

    run.completedAt = new Date();
  }

  private async commitResults(run: SymphonyRun): Promise<void> {
    try {
      await execAsync('git add -A', { cwd: run.workspacePath });

      const commitMessage = `Symphony: ${run.spec.name}

${run.summary || 'Task completed'}

Run ID: ${run.id}
`;

      await execAsync(`git commit -m "${commitMessage.replace(/"/g, '\\"')}"`, {
        cwd: run.workspacePath,
      });

      const { stdout } = await execAsync('git rev-parse HEAD', { cwd: run.workspacePath });
      run.commitSha = stdout.trim();

      await execAsync(`git push -u origin ${run.branch}`, { cwd: run.workspacePath });
    } catch (error) {
      console.error('Failed to commit symphony results:', error);
    }
  }

  private async sendSummary(run: SymphonyRun): Promise<void> {
    const summary = this.generateSummary(run);

    if (this.notification?.telegram) {
      await this.sendTelegram(this.notification.telegram, summary);
    }

    if (this.notification?.discord) {
      await this.sendDiscord(this.notification.discord, summary);
    }
  }

  private generateSummary(run: SymphonyRun): string {
    const status = run.status === 'completed' ? '✅' : run.status === 'failed' ? '❌' : '⏳';

    return `${status} Symphony Complete: ${run.spec.name}

📋 Task: ${run.spec.task.slice(0, 100)}...

📊 Status: ${run.status}
🌿 Branch: ${run.branch}
${run.commitSha ? `📌 Commit: ${run.commitSha.slice(0, 8)}` : ''}

📝 Summary:
${run.summary || 'No summary available'}

${
  run.changes?.length
    ? `📁 Changes (${run.changes.length} files):
${run.changes
  .slice(0, 5)
  .map((c) => `  ${c.status === 'added' ? '+' : c.status === 'deleted' ? '-' : 'M'} ${c.file}`)
  .join('\n')}`
    : ''
}

🔗 Review: Check the diff and accept/reject
`;
  }

  private async sendTelegram(chatId: string, message: string): Promise<void> {
    const botToken = process.env.TELEGRAM_BOT_TOKEN;
    if (!botToken) return;

    try {
      await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ chat_id: chatId, text: message }),
      });
    } catch (error) {
      console.error('Failed to send Telegram notification:', error);
    }
  }

  private async sendDiscord(webhookUrl: string, message: string): Promise<void> {
    try {
      await fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: message }),
      });
    } catch (error) {
      console.error('Failed to send Discord notification:', error);
    }
  }

  async acceptRun(runId: string): Promise<void> {
    const run = this.runs.get(runId);
    if (!run || run.status !== 'reviewing') {
      throw new Error('Run not found or not in review status');
    }

    try {
      await execAsync(`git checkout main`, { cwd: run.workspacePath });
      await execAsync(`git merge ${run.branch}`, { cwd: run.workspacePath });

      if (process.env.SYNC_TO_ORIGIN === 'true') {
        await execAsync('git push', { cwd: run.workspacePath });
      }

      run.reviewStatus = 'accepted';
    } catch (error) {
      console.error('Failed to accept run:', error);
      throw error;
    }
  }

  async rejectRun(runId: string, reason?: string): Promise<void> {
    const run = this.runs.get(runId);
    if (!run || run.status !== 'reviewing') {
      throw new Error('Run not found or not in review status');
    }

    try {
      await execAsync(`git checkout main`, { cwd: run.workspacePath });
      await execAsync(`git branch -D ${run.branch}`, { cwd: run.workspacePath });

      if (process.env.SYNC_TO_ORIGIN === 'true') {
        await execAsync(`git push origin --delete ${run.branch}`, { cwd: run.workspacePath });
      }

      run.reviewStatus = 'rejected';

      if (reason) {
        console.log(`Run ${runId} rejected: ${reason}`);
      }
    } catch (error) {
      console.error('Failed to reject run:', error);
    }
  }

  async retryRun(runId: string, agentExecutor: SymphonyAgentExecutor): Promise<SymphonyRun> {
    const oldRun = this.runs.get(runId);
    if (!oldRun) {
      throw new Error(`Run not found: ${runId}`);
    }

    const newSpec: SymphonySpec = {
      ...oldRun.spec,
      branch: undefined,
    };

    const newRun = await this.createRun(newSpec);
    return this.startRun(newRun.id, agentExecutor);
  }

  getRun(runId: string): SymphonyRun | undefined {
    return this.runs.get(runId);
  }

  listRuns(status?: SymphonyRun['status']): SymphonyRun[] {
    const runs = Array.from(this.runs.values());
    if (status) {
      return runs.filter((r) => r.status === status);
    }
    return runs;
  }

  async cleanup(runId: string): Promise<void> {
    const run = this.runs.get(runId);
    if (!run) return;

    try {
      if (fs.existsSync(run.workspacePath)) {
        fs.rmSync(run.workspacePath, { recursive: true, force: true });
      }
      this.runs.delete(runId);
    } catch (error) {
      console.error(`Failed to cleanup run ${runId}:`, error);
    }
  }
}

export interface SymphonyExecutionContext {
  workspacePath: string;
  task: string;
  branch: string;
}

export interface SymphonyExecutionResult {
  summary: string;
  changes: SymphonyChange[];
}

export interface SymphonyAgentExecutor {
  execute(context: SymphonyExecutionContext): Promise<SymphonyExecutionResult>;
}

export const symphonyOrchestrator = new SymphonyOrchestrator();

export class DefaultSymphonyExecutor implements SymphonyAgentExecutor {
  async execute(context: SymphonyExecutionContext): Promise<SymphonyExecutionResult> {
    console.log(`Executing symphony task in ${context.workspacePath}`);

    return {
      summary: 'Symphony task completed successfully',
      changes: [],
    };
  }
}
